In [1]:
from fastai.vision.all import *

In [2]:
path = untar_data(URLs.MNIST)
path.ls()

(#2) [Path('/home/sam/.fastai/data/mnist_png/testing'),Path('/home/sam/.fastai/data/mnist_png/training')]

In [3]:
dl = ImageDataLoaders.from_folder(
    path, 
    train="training", 
    seed = 21, 
    valid_pct=0.2
)

In [4]:
training_files = [ (path/"training"/label).ls() for label in dl.train.vocab ]
training_files

[(#5923) [Path('/home/sam/.fastai/data/mnist_png/training/0/32746.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/24105.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/22046.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/43727.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/30473.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/26055.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/51365.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/58647.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/19646.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/35923.png')...],
 (#6742) [Path('/home/sam/.fastai/data/mnist_png/training/1/38263.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/50667.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/40878.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/31950.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/31038.png'),Path('/home/sam/.fastai/data/mnist_png/traini

In [5]:
def createTensorsFromImage(images):
    tensors = torch.stack( [tensor(Image.open(file)) for file in images] )
    return tensors.view(-1, 28*28)

test = createTensorsFromImage(training_files[0])
test.shape

torch.Size([5923, 784])

In [6]:
tensors_list = [createTensorsFromImage(files) for files in training_files]
tensors_list

[tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  

In [7]:
torch.save(tensors_list, "training_data.pt")

Create some test data

In [10]:
test_files = [ (path/"testing"/label).ls() for label in dl.train.vocab ]
test_files

test_tensors_list = [createTensorsFromImage(files) for files in test_files]

In [11]:
torch.save(test_tensors_list, "test_data.pt")