In [7]:
from fastai.vision.all import *

In [8]:
path = untar_data(URLs.MNIST)
path.ls()

(#2) [Path('/home/sam/.fastai/data/mnist_png/testing'),Path('/home/sam/.fastai/data/mnist_png/training')]

In [9]:
dl = ImageDataLoaders.from_folder(
    path, 
    train="training", 
    seed = 21, 
    valid_pct=0.2
)

In [10]:
training_files = [ (path/"training"/label).ls() for label in dl.train.vocab ]
training_files

[(#5923) [Path('/home/sam/.fastai/data/mnist_png/training/0/32746.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/24105.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/22046.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/43727.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/30473.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/26055.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/51365.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/58647.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/19646.png'),Path('/home/sam/.fastai/data/mnist_png/training/0/35923.png')...],
 (#6742) [Path('/home/sam/.fastai/data/mnist_png/training/1/38263.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/50667.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/40878.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/31950.png'),Path('/home/sam/.fastai/data/mnist_png/training/1/31038.png'),Path('/home/sam/.fastai/data/mnist_png/traini

In [11]:
def createTensorsFromImage(images):
    tensors = torch.stack( [tensor(Image.open(file)) for file in images] )
    return tensors.view(-1, 28*28)

test = createTensorsFromImage(training_files[0])
test.shape

torch.Size([5923, 784])

In [12]:
tensors_list = [createTensorsFromImage(files) for files in training_files]
tensors_list

[tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8),
 tensor([[0, 0, 0,  

In [13]:
torch.save(tensors_list, "training_data.pt")

Create some test data

In [16]:
test_files = [ (path/"testing"/label).ls() for label in dl.train.vocab ]
test_files

[(#980) [Path('/home/sam/.fastai/data/mnist_png/testing/0/2087.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/7693.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/9634.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/6959.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/4720.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/8921.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/2811.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/269.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/8681.png'),Path('/home/sam/.fastai/data/mnist_png/testing/0/525.png')...],
 (#1135) [Path('/home/sam/.fastai/data/mnist_png/testing/1/4574.png'),Path('/home/sam/.fastai/data/mnist_png/testing/1/2444.png'),Path('/home/sam/.fastai/data/mnist_png/testing/1/5477.png'),Path('/home/sam/.fastai/data/mnist_png/testing/1/2355.png'),Path('/home/sam/.fastai/data/mnist_png/testing/1/9796.png'),Path('/home/sam/.fastai/data/mnist_png/testing/1/5552.png'),Path('/home/sam/.f

In [ ]:
random.seed(555)

def getRandomTensor(files):
    index = random.randint( 0, len(files) - 1 )
    return tensor(Image.open(files[index])).view(28*28)

test = getRandomTensor(test_files[0])
test

In [25]:
test_tensors = [getRandomTensor(file) for file in test_files]
len(test_tensors)

10

In [26]:
torch.save(test_tensors, "test_data.pt")